language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

notifications:
  email: false

install:
   composer install --no-interaction --prefer-dist